server:
  port: 9090
  ssl:
    key-store: classpath:cert-chain.p12
    key-store-password: root@2580
    keyStoreType: PKCS12
    #keyAlias: tomcat
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: SALEX-API-GATEWAY-SERVICE
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: ROUTE-XDIL
          uri: http://localhost:8081
          predicates:
            - Path=/v1/**
          filters:
            - name: CacheRequestBody
        - id: ROUTE-XDIL
          uri: http://localhost:8082
          predicates:
            - Path=/v1/**
          filters:
            - name: CacheRequestBody
        - id: ROUTE-XDIL
          uri: http://localhost:8083
          predicates:
            - Path=/v1/**
          filters:
            - name: CacheRequestBody

        - id: ROUTE-D
          uri: http://localhost:8081
          predicates:
            - Path=/file/**
        - id: ROUTE-E
          uri: http://localhost:8082
          predicates:
            - Path=/file/**
        - id: ROUTE-F
          uri: http://localhost:8083
          predicates:
            - Path=/file/**


        - id: ROUTE-RECRUTINOW
          uri: http://localhost:8091
          predicates:
            - Path=/rn/**
        - id: ROUTE-RECRUTINOW
          uri: http://localhost:8092
          predicates:
            - Path=/rn/**
        - id: ROUTE-RECRUTINOW
          uri: http://localhost:8093
          predicates:
            - Path=/rn/**